FROM bellsoft/liberica-openjdk-alpine-musl:17.0.4

ARG UID=1001
RUN adduser -S appuser -u $UID

ENV HOME=/app
WORKDIR $HOME

RUN chown $UID $HOME \
    && chmod "g+rwX" $HOME \
    && chown $UID:root $HOME
COPY --chown=$UID:root build/libs/interlis-repo-checker-*-exec.jar $HOME/application.jar

USER $UID
EXPOSE 8080

ENV LOG4J_FORMAT_MSG_NO_LOOKUPS=true

CMD java -XX:MaxRAMPercentage=80.0 -jar application.jar
